In [1]:
%config Completer.use_jedi = False
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import os

from scipy.stats import skew
#%matplotlib inline
plt.style.use('ggplot')

#funcion parachekar si los eneros estan completos
def mescompleto(x,ano):
    a=x[x.index.year==ano].isnull().sum()==0
    return a
#retorna años con los meses completos
def anosconmesescompletos(x):
    ano=range(1981,2017)
    idx=[]
    for i in range(len(ano)):
        if mescompleto(x,ano[i]):
            idx.append(ano[i])
    return idx

#retorna la serie con los meses completos para luego calcular los estadisticos
def seriefinal(x):

    idx=anosconmesescompletos(x)
    lista=[]
    for i in range(len(idx)):
        lista.append(x[x.index.year==idx[i]])
    
    if len(lista)>15:#mayor a 15 ano
        return pd.concat(lista)#remodificar esta funcion
    else:
        return []

def proportiondry(x):
    def mayorque(y):
        return y>0.1
    drydays=len(x)-np.sum(x.apply(mayorque))
    return float(drydays)/len(x)

def autocovariance(Xi, k=1):
    N = np.size(Xi)
    Xs = np.average(Xi)
    autoCov = 0
    for i in np.arange(0, N-k):
        autoCov += ((Xi[i+k])-Xs)*(Xi[i]-Xs)
    return (1.0/(N-1))*autoCov

def estadisticosprec(x):
    result=[]
    a=x.dropna()
    #si se tiene menor a 10 años no contar
    if len(a)==0:
        return [None]
    result.append(np.mean(a))
    result.append(np.var(a))
    result.append(autocovariance(a))
    result.append(proportiondry(a))
    return result

#crea una tabla de los estadisticos extraidos una vez usado la fucion estadisticosprec
def crearTablaEst(x,names=['x','y','mean1h','var1h','autocov1h','dryperiod1h']):
    
    val=x.transpose()
    val.reset_index(drop=True, inplace=True)
    #pos=posiciones#posiciones.loc[final_station,:]
    #pos.reset_index(drop=True, inplace=True)
    #df=pd.concat([pos, pd.DataFrame(np.matrix(val))], axis=1)
    df=pd.concat([pd.DataFrame(np.matrix(val))], axis=1)
    df.columns=names
    
    return df

def factores(a,b):
    if a==0.0 or b==0.0:
        return a
    else:
        return float(a)/b

In [5]:
os.chdir('D:/Proyectos_GitHub/Bartlet-Lewis_Regionalization/data/ValidacionIndependiente/iMHEA_processed/Hourly')
files=['iMHEA_PIU_03_1hr_processed.csv','iMHEA_PIU_02_1hr_processed.csv','iMHEA_PIU_06_1hr_processed.csv','iMHEA_PIU_07_1hr_processed.csv',
      'iMHEA_CHA_01_1hr_processed.csv','iMHEA_CHA_02_1hr_processed.csv','iMHEA_HUA_01_1hr_processed.csv',
      'iMHEA_HMT_01_1hr_processed.csv']#,'iMHEA_TAM_02_1hr_processed.csv','iMHEA_TAM_01_1hr_processed.csv']

In [18]:
#file='D:/Proyectos_GitHub/Bartlet-Lewis_Regionalization/data/ValidacionIndependiente/iMHEA_processed/Hourly/iMHEA_PIU_01_1hr_processed.csv'
result=[]
SAVE_PATH='D:/Proyectos_GitHub/Bartlet-Lewis_Regionalization/data/ValidacionIndependiente/Validation_points/'
file_names=['FEB_PIU_03_1hr.csv','FEB_PIU_02_3hr.csv','FEB_PIU_06_3hr.csv','FEB_PIU_07_3hr.csv',
      'FEB_CHA_01_3hr.csv','FEB_CHA_02_3hr.csv','FEB_HUA_01_3hr.csv',
      'FEB_HMT_01_3hr.csv']#,'FEB_TAM_02_3hr.csv','FEB_TAM_01_3hr.csv']

for k,file in enumerate(files):
    dateparse = lambda x: datetime.strptime(x, '%d/%m/%Y %H:%M:%S')
    gauge=pd.read_csv(file,parse_dates=['Date'],date_parser=dateparse)
    gauge=gauge.set_index('Date')
    gauge=gauge.astype('float')
    ESTS=[]
    acumn=['24h','1h','3h','6h','12h','18h']
    for level in acumn:
        gauge_acum=gauge.dropna().groupby(pd.Grouper(freq=level)).agg(np.sum)
        
        if level == '3h':
            feb=gauge_acum.loc[np.in1d(gauge_acum.index.month, 2),['Rainfall mm']].dropna()
            feb.to_csv(SAVE_PATH+file_names[k])
            
        ESTS.append(gauge_acum.loc[np.in1d(gauge_acum.index.month, 2),['Rainfall mm']].dropna().apply(estadisticosprec, axis=0))

In [21]:
feb

Empty DataFrame
Columns: [Rainfall mm]
Index: []

In [ ]:
ESTS=[]
acumn=['24h','1h','3h','6h','12h','18h']
for level in acumn:
    gauge_acum=gauge.dropna().groupby(pd.Grouper(freq=level)).agg(np.sum)
    ESTS.append(gauge_acum.loc[np.in1d(gauge_acum.index.month, 2),['Rainfall mm']].dropna().apply(estadisticosprec, axis=0))

result=[]
agregados=[24,1,3,6,12,18]
for i,stat in enumerate(ESTS):
    names=[]#['x','y']
    names=names+['mean{}'.format(agregados[i]),'var{}'.format(agregados[i]),'autocov{}'.format(agregados[i]),'dryperiod{}'.format(agregados[i])]
    result.append(crearTablaEst(stat,names))

In [28]:
df=pd.concat(result,axis=1)
df=df.loc[:,~df.columns.duplicated()]
df

,mean24,var24,autocov24,dryperiod24,mean1,var1,autocov1,dryperiod1,mean3,var3,...,autocov6,dryperiod6,mean12,var12,autocov12,dryperiod12,mean18,var18,autocov18,dryperiod18
0,4.845836,46.531074,5.111579,0.196429,0.20191,0.463236,0.241073,0.727679,0.605729,2.332713,...,2.113754,0.464286,2.422918,19.174904,2.926529,0.330357,3.814903,39.680176,4.969191,0.24

In [30]:
gauge_acum=gauge.dropna().groupby(pd.Grouper(freq='3h')).agg(np.sum)
feb=gauge_acum.loc[np.in1d(gauge_acum.index.month, 2),['Rainfall mm']]

In [34]:
feb

                     Rainfall mm
Date
2014-02-01 00:00:00       0.0775
2014-02-01 03:00:00       0.6749
2014-02-01 06:00:00       1.6371
2014-02-01 09:00:00       1.3655
2014-02-01 12:00:00       2.8859
...                          ...
2015-02-28 09:00:00       0.1833
2015-02-28 12:00:00       0.0000
2015-02-28 15:00:00       0.7333
2015-02-28 18:00:00       0.0667
2015-02-28 21:00:00       0.1333

[448 rows x 1 columns]